"""
Django settings for email_automation project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
import json
import base64
import dj_database_url
from pathlib import Path
from email.headerregistry import Address
from logging.handlers import SysLogHandler

# Load environment variables from .env file if it exists (local development)
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', '0') == '1'

# Check if running on Vercel
IS_VERCEL = os.environ.get('VERCEL', '') == '1'
cloud_platform = os.environ.get('CLOUD_PLATFORM', '')

# Firebase credentials handling for cloud platforms
if cloud_platform in ['DIGITAL_OCEAN', 'VERCEL'] or IS_VERCEL:
    firebase_cred = os.environ.get('FIREBASE_ENCODED', '')
    firebase_cred_path = os.environ.get('FIREBASE_CRED_PATH', '/tmp/firebase_cred.json')
    
    if firebase_cred:
        try:
            decoded_bytes = base64.b64decode(firebase_cred)
            decoded_json = json.loads(decoded_bytes.decode('utf-8'))
            
            # Write to /tmp on Vercel (read-only filesystem except /tmp)
            with open(firebase_cred_path, 'w') as f:
                json.dump(decoded_json, f, indent=4)
        except Exception as e:
            print(f"Warning: Could not decode Firebase credentials: {e}")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 
    'django-insecure-ksg!i&r49#t+x6*f^v#glkvhg_nfb^24r%l7im#ti-(it!5(y6' if DEBUG else None
)

if not SECRET_KEY and not DEBUG:
    raise ValueError("SECRET_KEY environment variable is required in production")

# Allowed hosts configuration
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
elif IS_VERCEL:
    # Allow all Vercel deployment domains and custom domains
    ALLOWED_HOSTS = [
        '.vercel.app',
        '.now.sh',
        'localhost',
    ]
    # Add custom domain if specified
    custom_domain = os.environ.get('DOMAIN', '')
    if custom_domain:
        # Extract hostname from domain URL
        from urllib.parse import urlparse
        parsed = urlparse(custom_domain)
        hostname = parsed.netloc or parsed.path
        if hostname:
            ALLOWED_HOSTS.append(hostname)
    
    # Add additional allowed hosts from env
    additional_hosts = os.environ.get('ALLOWED_PROD_HOSTS', '')
    if additional_hosts:
        ALLOWED_HOSTS.extend([h.strip() for h in additional_hosts.split(',') if h.strip()])
else:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_PROD_HOSTS', '').replace(' ', '').split(',')

# CSRF trusted origins for Vercel
CSRF_TRUSTED_ORIGINS = []
if IS_VERCEL:
    CSRF_TRUSTED_ORIGINS = [
        'https://*.vercel.app',
        'https://*.now.sh',
    ]
    custom_domain = os.environ.get('DOMAIN', '')
    if custom_domain:
        CSRF_TRUSTED_ORIGINS.append(custom_domain)

DOMAIN = os.environ.get('DOMAIN', 'http://localhost:8000')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 3rd party
    'encrypted_model_fields',
    'tailwind',
    'theme',
    'corsheaders',
    # Note: django_celery_beat requires database access, may need to be conditionally loaded
    'django_celery_beat',

    # my apps
    'automail',
    'user',
    'blog'
]

# Only add browser reload in development
if DEBUG:
    INSTALLED_APPS.append('django_browser_reload')

# Field encryption key
FIELD_ENCRYPTION_KEY = os.environ.get(
    'FIELD_ENCRYPTION_KEY' if DEBUG else 'PROD_FIELD_ENCRYPTION_KEY',
    os.environ.get('FERNET_KEY', '')  # Fallback to FERNET_KEY
)

LOGIN_URL = '/user/login/'

AUTH_USER_MODEL = "user.User" 

TAILWIND_APP_NAME = 'theme'

RATELIMIT_VIEW = 'email_automation.views.rate_limiter_view'

INTERNAL_IPS = [
    "127.0.0.1",
]

# Celery configuration
CELERY_BROKER_URL = os.environ.get('REDIS_PROD_HOST', 'redis://127.0.0.1:6379').strip()

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

CELERYBEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
CELERY_IMPORTS = ['utils.tasks',]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_ratelimit.middleware.RatelimitMiddleware',
    'email_automation.middlewares.RateLimitJsonResponseMiddleware',
    'email_automation.middlewares.FileUploadMiddleware',
]

# Add browser reload middleware only in development
if DEBUG:
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")

ROOT_URLCONF = 'email_automation.urls'

# Email configuration
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = Address(display_name="AtMailWin", addr_spec=EMAIL_HOST_USER)
    EMAIL_USE_SSL = True

EMAIL_FROM_SIGNATURE = 'Best regards, Atmailwin Team'
EMAIL_FROM = 'info@atmailwin.com'
EMAIL_FROM_NAME = 'AtMailWin'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.joinpath("templates"),
            BASE_DIR.joinpath("templates", "html"),
            BASE_DIR.joinpath("templates", "html", "error"),
            BASE_DIR.joinpath("templates", "html", "authentication"),
            BASE_DIR.joinpath("templates", "html", "terms"),
            BASE_DIR.joinpath("templates", "html", "blog"),
            BASE_DIR.joinpath("templates", "html", "email-product"),
            BASE_DIR.joinpath("templates", "html", "email-product", "templates"),
            BASE_DIR.joinpath("templates", "html", "email-product", "campaign"),
            BASE_DIR.joinpath("templates", "html", "email-product", "configuration"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'email_automation.context_processors.secrets',
            ],
            'libraries': {
                'custom_tags': 'email_automation.templatetags.custom_tags',
            }
        },
    },
]

WSGI_APPLICATION = 'email_automation.wsgi.application'


# Database configuration
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

if DEBUG and not os.environ.get('DATABASE_URL') and not os.environ.get('POSTGRES_URL'):
    # Local SQLite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
        'OPTIONS': {
            "timeout": 20,
        }
    }
else:
    # Production PostgreSQL via dj-database-url
    # Supports DATABASE_URL, POSTGRES_URL, or Neon/Supabase URLs
    database_url = os.environ.get('DATABASE_URL') or os.environ.get('POSTGRES_URL', '')
    
    if database_url:
        DATABASES = {
            'default': dj_database_url.config(
                default=database_url,
                conn_max_age=600,
                conn_health_checks=True,
                ssl_require=True,
            )
        }
        # Ensure PostgreSQL engine
        DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
    else:
        raise ValueError("DATABASE_URL or POSTGRES_URL environment variable is required")

# Cache configuration
redis_url = os.environ.get('REDIS_PROD_HOST', 'redis://127.0.0.1:6379')
redis_password = os.environ.get('REDIS_PASSWORD', '')

if IS_VERCEL and not redis_url.startswith('redis://'):
    # Skip Redis cache on Vercel if not configured
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f"{redis_url}/0",
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'PASSWORD': redis_password if redis_password else None
            },
            'TIMEOUT': 300,
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR.joinpath('staticfiles', 'static')

STATICFILES_DIRS = [
    BASE_DIR.joinpath('templates'),
    BASE_DIR.joinpath('templates', 'js'),
    BASE_DIR.joinpath('templates', 'css'),
    BASE_DIR.joinpath('templates', 'assets'),
]

# WhiteNoise configuration for serving static files on Vercel
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise settings
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True


# Media files configuration
MEDIA_ROOT = BASE_DIR.joinpath('media')
MEDIA_URL = '/media/'
MEDIA_DOMAIN = os.environ.get('DOMAIN', 'http://localhost:8000')

# Google Cloud Storage for media files (production)
if not DEBUG:
    firebase_cred_path = os.environ.get('FIREBASE_CRED_PATH', '/tmp/firebase_cred.json')
    bucket_name = os.environ.get('BUCKET_NAME', '')
    project_id = os.environ.get('PROJECT_ID', '')
    
    if bucket_name and project_id and os.path.exists(firebase_cred_path):
        try:
            from google.oauth2 import service_account
            
            DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
            GS_BUCKET_NAME = bucket_name
            GS_PROJECT_ID = project_id
            GS_CREDENTIALS = service_account.Credentials.from_service_account_file(firebase_cred_path)
            GS_DEFAULT_ACL = "publicRead"
            GS_QUERYSTRING_AUTH = True
            GS_FILE_OVERWRITE = False
        except Exception as e:
            print(f"Warning: Could not configure Google Cloud Storage: {e}")


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'formatters': {
        'verbose': {
            'format': '[email_automation] %(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Only enable these if you have HTTPS (Vercel provides this)
    if IS_VERCEL:
        SECURE_SSL_REDIRECT = False  # Vercel handles SSL
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
